# Generated by Django 5.0.6 on 2024-06-12 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_administrador', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='Foto de perfil del administrador')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del administrador')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación del administrador')),
                ('blame_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario culpable de guardar los datos del nuevo administrador')),
            ],
            options={
                'ordering': ('-creado', 'apellidos', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='Foto de perfil del alumno')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del alumno')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación del alumno')),
                ('blame_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario culpable de guardar los datos del nuevo alumno')),
            ],
            options={
                'ordering': ('-creado', 'apellidos', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profesor', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles', verbose_name='Foto de perfil del profesor')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del profesor')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación del profesor')),
                ('blame_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario culpable de guardar los datos del nuevo profesor')),
            ],
            options={
                'ordering': ('-creado', 'apellidos', 'nombre'),
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_curso', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('imagen_curso', models.ImageField(blank=True, null=True, upload_to='img-cursos', verbose_name='Imágen del curso')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del curso')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación del curso')),
                ('alumnos', models.ManyToManyField(blank=True, to='core.alumno')),
                ('blame_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario culpable de guardar los datos del nuevo curso')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profesor')),
            ],
        ),
    ]
