# Generated by Django 5.0.6 on 2024-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_curso_options_remove_curso_profesor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor',
            field=models.ManyToManyField(blank=True, to='core.profesor'),
        ),
    ]
