# Generated by Django 5.0.6 on 2024-06-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_curso_alumnos_alumno_cursos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
