# Generated by Django 5.0.6 on 2024-06-12 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profesor_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_precio', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('cantidad', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación del precio')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación del precio')),
            ],
            options={
                'ordering': ('-creado', 'cantidad'),
            },
        ),
    ]
