# Generated by Django 5.0.6 on 2024-06-12 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='precio',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.curso', verbose_name='Curso'),
            preserve_default=False,
        ),
    ]
