# Generated by Django 5.0.6 on 2024-06-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_administrador_options_alter_profesor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='imagen_curso',
            field=models.ImageField(blank=True, null=True, upload_to='img-cursos', verbose_name='Imagen del curso'),
        ),
    ]
